### ISSUE TITLE
should go get have made the toggl command available automatically?

### ISSUE THREAD

**Issue by cori** [sachaos/toggl#2]
After running `go get -d github.com/sachaos/toggl` I had to make an alias to point to the toggl command. I am completely unfamiliar with go, so I'm not sure what I should have expected. Is this the result of my go environment being incorrectly set up (for example not having ~/go/bin in my path)?

**Comment by sachaos** [comment]
@cori You should add `$GOPATH/bin` to `$PATH`.

**Comment by cori** [comment]
That's kind of what I thought. Thanks!
