### ISSUE TITLE
toggl v8 API is deprecated

### ISSUE THREAD

**Issue by tobischo** [sachaos/toggl#8]
I am using this toggl command line tool quite extensively and got informed today that toggl will deprecate the v8 API endpoints.

https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html

Are you still using it and planning to update it already to the v9 API?

**Comment by sachaos** [comment]
@tobischo Thank you for the information.
I'm not using this command.
But the PR is welcomed.

**Comment by tobischo** [comment]
Addressed it in #9

**Comment by tobischo** [comment]
Closing as #9 was merged
